### ISSUE TITLE
Has the rating combination changed?

### ISSUE THREAD

**Issue by pratik60** [elmaano/sbc#5]
<img width="1065" alt="screen shot 2018-05-08 at 01 05 18" src="https://user-images.githubusercontent.com/2249430/39730855-e83ac9ee-525b-11e8-9cad-e7d4c1a0d7aa.png">

I get an 82 rated squad, not an 83.
<img width="1204" alt="screen shot 2018-05-08 at 01 05 04" src="https://user-images.githubusercontent.com/2249430/39730856-e8560ca4-525b-11e8-8a51-ee1c437e732c.png">

**Comment by amaanm** [comment]
There is sometimes an issue with the web-app which doesn't calculate the correct rating. If you go back to the SBC menu then click on the SBC again, it should have the correct rating. I've had to do that many times.

**Comment by pratik60** [comment]
Going to an actual sbc (icon for example), and putting the same squad generates an 83 rated. Wonder if because it was a concept squad we saw other results.
